insert into Person (Id, first_name, last_name) values (1L,'Yatin','Khadilkar');
insert into Person (Id, first_name, last_name) values (2L,'Kenzie', 'Moon');
insert into Person (Id, first_name, last_name) values (3L,'Madison', 'Waters');
insert into Person (Id, first_name, last_name) values (4L,'Rowan','Ho');
insert into Person (Id, first_name, last_name) values (5L,'Raphael', 'Melendez');
insert into Person (Id, first_name, last_name) values (6L,'Denisse', 'Pott');
insert into Person (Id, first_name, last_name) values (7L,'Bailey', 'Blankenship');
insert into Person (Id, first_name, last_name) values (8L,'Kaitlin', 'Lopez');
insert into Person (Id, first_name, last_name) values (9L,'Porter', 'Stafford');
insert into Person (Id, first_name, last_name) values (10L,'Jamiya', 'Benitez');
insert into Person (Id, first_name, last_name) values (11L,'Aryan', 'Woods');
insert into Person (Id, first_name, last_name) values (12L,'Meghan', 'George');
insert into Person (Id, first_name, last_name) values (13L,'Yatin Jr.', 'Khadilkar');
insert into Person (Id, first_name, last_name) values (14L,'Kenzie Jr.','Moon');
insert into Person (Id, first_name, last_name) values (15L,'Madison Jr.','Waters');
insert into Person (Id, first_name, last_name) values (16L,'Rowan Jr.','Ho');
insert into Person (Id, first_name, last_name) values (17L,'Bailey Jr.','Blankenship');
insert into Person (Id, first_name, last_name) values (18L,'Kaitlin Jr.','Lopez');
insert into Person (Id, first_name, last_name) values (19L,'Porter Jr.','Stafford');
insert into Person (Id, first_name, last_name) values (20L,'Jamiya Jr.','Benitez');
insert into Person (Id, first_name, last_name) values (21L,'Aryan Jr.','Woods');
insert into Person (Id, first_name, last_name) values (22L,'Meghan Jr.','George');
insert into Person (Id, first_name, last_name) values (23L,'Raphael Jr.','Melendez');
insert into Person (Id, first_name, last_name) values (24L,'Denisse Jr.','Pott');